---
- name: Harden ssh by NOT accepting root login
  become: true  
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present 
    validate: 'sshd -t -f %s'
  with_items:
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"

- name: Restart ssh
  ansible.builtin.systemd: 
    name: sshd.service
    state: restarted 

    