---
- name: Check linux-distro
  shell: . /etc/os-release; echo "$NAME"
  register: OS_RELEASE

- name: Distribute the Netplan config yaml-file
  ansible.builtin.copy:
    src: roles/dist-files/files/01-network-manager-all.yaml
    dest: /etc/netplan/01-network-manager-all.yaml
    owner: root
    group: root
    mode: '0644'
  become: true
  when: OS_RELEASE == "Ubuntu"

- name: Apply changes to Netplan config
  shell: netplan apply
  become: true
  when: OS_RELEASE == "Ubuntu"

- name: Add an Ethernet connection with static IP configuration
  community.general.nmcli:
    conn_name: my-eth0
    ifname: eth0
    type: ethernet
    ip4: 192.0.2.100/24
    gw4: 192.0.2.1
    state: present

- name: Add two IPv4 DNS server addresses
  community.general.nmcli:
    conn_name: my-eth0
    type: ethernet
    dns4:
    - 8.8.8.8
    - 1.1.1.1
    state: present