---
- name: Add Zabbix repository Suse distro
  ansible.builtin.shell: |
    rpm -Uvh --nosignature https://repo.zabbix.com/zabbix/6.4/sles/15/x86_64/zabbix-release-6.4-1.sles15.noarch.rpm
    zypper --gpg-auto-import-keys refresh 'Zabbix Official Repository'
  when:
    - ansible_os_family == 'Suse'

- name: Install Zabbix for Suse/OpenSuse
  community.general.zypper:
    name: zabbix-agent2 
    state: present
    update_cache: true
  when:
    - ansible_os_family == 'Suse'

- name: Add Zabbix repository Ubuntu 20.04
  ansible.builtin.shell: |
    wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb
    dpkg -i zabbix-release_6.4-1+ubuntu20.04_all.deb
  when: 
    - ansible_distribution_version == '20.04'

- name: Add Zabbix repository Ubuntu 22.04
  ansible.builtin.shell: |
     wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
     dpkg -i zabbix-release_6.4-1+ubuntu22.04_all.deb
  when: 
    - ansible_distribution_version == '22.04'

- name: Update the repository cache 
  ansible.builtin.apt:
    update_cache: yes
  when: 
    ansible_facts['distribution'] == "Ubuntu" or 
    ansible_facts['distribution'] == "Debian"

- name: Install the package "zabbix-agent2"
  ansible.builtin.apt:
    name: zabbix-agent2 
    state: present 
  when: 
    ansible_facts['distribution'] == "Ubuntu" or 
    ansible_facts['distribution'] == "Debian"

- name: Stop zabbix-agent2
  systemd:
    name: zabbix-agent2.service
    state: stopped
    enabled: yes
    daemon_reload: yes

- name: Copy template file to /etc/zabbix/zabbix_agent2.conf
  ansible.builtin.template:
    src: ~/Documents/git/vm-mgmt/ansible/roles/install-zabbix/templates/zabbix.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'

- name: Add hostname to Zabbix config-file
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    regexp: "^Hostname="
    line: "Hostname={{ ansible_hostname }}"
    state: present

- name: Add PSKidentity to Zabbix config-file
  lineinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    regexp: "^TLSPSKIdentity="
    line: "TLSPSKIdentity={{ ansible_hostname }}"
    state: present

- name: Create and add PSK code to file
  ansible.builtin.shell: |
    openssl rand -hex 32 > /etc/zabbix/zabbix_agent2.psk

- name: Print PSK code
  ansible.builtin.shell: |
    cat /etc/zabbix/zabbix_agent2.psk
  register: psk_code

- name: Start zabbix-agent2
  systemd:
    name: zabbix-agent2.service
    state: started
    daemon_reload: yes

- name: Print PSK code with the hostname 
  ansible.builtin.debug:
    msg:
    - "The virtualmachine name: '{{ ansible_hostname  }}'"
    - "The PSK code is '{{ psk_code }}'. Please retain this for later use."